-- Create city_run_setups table
-- Only created when a recurring run series is configured.
-- Standalone city_runs have cityRunSetupId = NULL.
CREATE TABLE "city_run_setups" (
  "id"        TEXT NOT NULL,
  "dayOfWeek" TEXT NOT NULL,
  "runClubId" TEXT,
  "name"      TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "city_run_setups_pkey" PRIMARY KEY ("id")
);

-- FK from city_run_setups to run_clubs
ALTER TABLE "city_run_setups"
  ADD CONSTRAINT "city_run_setups_runClubId_fkey"
  FOREIGN KEY ("runClubId") REFERENCES "run_clubs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Index
CREATE INDEX "city_run_setups_runClubId_idx" ON "city_run_setups"("runClubId");

-- Add cityRunSetupId to city_runs
-- null = standalone run; set = recurring (generated by a CityRunSetup)
ALTER TABLE "city_runs" ADD COLUMN IF NOT EXISTS "cityRunSetupId" TEXT;

-- FK from city_runs to city_run_setups
ALTER TABLE "city_runs"
  ADD CONSTRAINT "city_runs_cityRunSetupId_fkey"
  FOREIGN KEY ("cityRunSetupId") REFERENCES "city_run_setups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Index
CREATE INDEX "city_runs_cityRunSetupId_idx" ON "city_runs"("cityRunSetupId");
