import type { WorkoutType } from "@prisma/client";
import {
  PACE_ANCHOR_CURRENT_BUILDUP,
  PACE_ANCHOR_MP_SIMULATION,
} from "@/lib/training/goal-pace-calculator";

export type CatalogueSeedRow = {
  name: string;
  /** Optional; defaults to kebab-case from `name` at seed time. */
  slug?: string | null;
  workoutType: WorkoutType;
  description: string | null;
  intendedPhase: string[];
  isQuality: boolean;
  isLongRunQuality: boolean;
  isMP: boolean;
  isLadder: boolean;
  paceAnchor: string;
  mpFraction: number | null;
  mpTotalMiles: number | null;
  mpPaceOffsetSecPerMile: number | null;
  mpBlockPosition: string | null;
  mpBlockProgression: string;
  ladderStepMeters: number | null;
  minLadderMeters: number | null;
  maxLadderMeters: number | null;
  progressionIndex: number | null;
  workBaseReps: number | null;
  workBaseRepMeters: number | null;
  workBaseMiles: number | null;
  recoveryDistanceMeters: number | null;
  warmupMiles: number | null;
  warmupPaceOffsetSecPerMile: number | null;
  cooldownMiles: number | null;
  cooldownPaceOffsetSecPerMile: number | null;
  workPaceOffsetSecPerMile: number | null;
  workBasePaceOffsetSecPerMile: number | null;
  recoveryPaceOffsetSecPerMile: number | null;
  notes: string | null;
};

/** Canonical rows for API seed and `scripts/seed-catalogue.ts`. */
export const SEED_CATALOGUE_ROWS: CatalogueSeedRow[] = [
  {
    name: "Up and Over",
    workoutType: "Intervals",
    description: "Pyramid ladder: step 200m, min 200m, max 800m.",
    intendedPhase: ["base", "build", "peak"],
    isQuality: true,
    isLongRunQuality: false,
    isMP: false,
    isLadder: true,
    paceAnchor: PACE_ANCHOR_CURRENT_BUILDUP,
    mpFraction: null,
    mpTotalMiles: null,
    mpPaceOffsetSecPerMile: null,
    mpBlockPosition: null,
    mpBlockProgression: "flat",
    ladderStepMeters: 200,
    minLadderMeters: 200,
    maxLadderMeters: 800,
    progressionIndex: 1,
    workBaseReps: null,
    workBaseRepMeters: null,
    workBaseMiles: null,
    recoveryDistanceMeters: null,
    warmupMiles: 1.5,
    warmupPaceOffsetSecPerMile: null,
    cooldownMiles: 1.5,
    cooldownPaceOffsetSecPerMile: null,
    workPaceOffsetSecPerMile: null,
    workBasePaceOffsetSecPerMile: -30,
    recoveryPaceOffsetSecPerMile: null,
    notes: "Pyramid ladder: step 200m, min 200m, max 800m.",
  },
  {
    name: "Tempo",
    workoutType: "Tempo",
    description: null,
    intendedPhase: ["base", "build", "peak"],
    isQuality: true,
    isLongRunQuality: false,
    isMP: false,
    isLadder: false,
    paceAnchor: PACE_ANCHOR_CURRENT_BUILDUP,
    mpFraction: null,
    mpTotalMiles: null,
    mpPaceOffsetSecPerMile: null,
    mpBlockPosition: null,
    mpBlockProgression: "flat",
    ladderStepMeters: null,
    minLadderMeters: null,
    maxLadderMeters: null,
    progressionIndex: 1,
    workBaseReps: null,
    workBaseRepMeters: null,
    workBaseMiles: null,
    recoveryDistanceMeters: null,
    warmupMiles: 1.5,
    warmupPaceOffsetSecPerMile: null,
    cooldownMiles: 1.0,
    cooldownPaceOffsetSecPerMile: null,
    workPaceOffsetSecPerMile: 30,
    workBasePaceOffsetSecPerMile: null,
    recoveryPaceOffsetSecPerMile: null,
    notes: null,
  },
  {
    name: "Interval",
    workoutType: "Intervals",
    description: null,
    intendedPhase: ["base", "build", "peak"],
    isQuality: true,
    isLongRunQuality: false,
    isMP: false,
    isLadder: false,
    paceAnchor: PACE_ANCHOR_CURRENT_BUILDUP,
    mpFraction: null,
    mpTotalMiles: null,
    mpPaceOffsetSecPerMile: null,
    mpBlockPosition: null,
    mpBlockProgression: "flat",
    ladderStepMeters: null,
    minLadderMeters: null,
    maxLadderMeters: null,
    progressionIndex: 2,
    workBaseReps: 6,
    workBaseRepMeters: 800,
    workBaseMiles: null,
    recoveryDistanceMeters: null,
    warmupMiles: 1.5,
    warmupPaceOffsetSecPerMile: null,
    cooldownMiles: 1.5,
    cooldownPaceOffsetSecPerMile: null,
    workPaceOffsetSecPerMile: null,
    workBasePaceOffsetSecPerMile: -30,
    recoveryPaceOffsetSecPerMile: null,
    notes: null,
  },
  {
    name: "Long Run",
    workoutType: "LongRun",
    description: null,
    intendedPhase: ["base", "build", "peak", "taper"],
    isQuality: false,
    isLongRunQuality: false,
    isMP: false,
    isLadder: false,
    paceAnchor: PACE_ANCHOR_CURRENT_BUILDUP,
    mpFraction: null,
    mpTotalMiles: null,
    mpPaceOffsetSecPerMile: null,
    mpBlockPosition: null,
    mpBlockProgression: "flat",
    ladderStepMeters: null,
    minLadderMeters: null,
    maxLadderMeters: null,
    progressionIndex: 1,
    workBaseReps: null,
    workBaseRepMeters: null,
    workBaseMiles: null,
    recoveryDistanceMeters: null,
    warmupMiles: null,
    warmupPaceOffsetSecPerMile: null,
    cooldownMiles: null,
    cooldownPaceOffsetSecPerMile: null,
    workPaceOffsetSecPerMile: 90,
    workBasePaceOffsetSecPerMile: null,
    recoveryPaceOffsetSecPerMile: null,
    notes: null,
  },
  {
    name: "Long Run Quality",
    workoutType: "LongRun",
    description:
      "Easy first; final block at imprinted goal race pace. mpFraction scales with plan ladder index.",
    intendedPhase: ["build", "peak"],
    isQuality: true,
    isLongRunQuality: true,
    isMP: true,
    isLadder: false,
    paceAnchor: PACE_ANCHOR_MP_SIMULATION,
    mpFraction: 0.4,
    mpTotalMiles: null,
    mpPaceOffsetSecPerMile: null,
    mpBlockPosition: "BACK_HALF",
    mpBlockProgression: "flat",
    ladderStepMeters: null,
    minLadderMeters: null,
    maxLadderMeters: null,
    progressionIndex: 2,
    workBaseReps: null,
    workBaseRepMeters: null,
    workBaseMiles: null,
    recoveryDistanceMeters: null,
    warmupMiles: null,
    warmupPaceOffsetSecPerMile: null,
    cooldownMiles: null,
    cooldownPaceOffsetSecPerMile: null,
    workPaceOffsetSecPerMile: 0,
    workBasePaceOffsetSecPerMile: null,
    recoveryPaceOffsetSecPerMile: null,
    notes:
      "Easy first; final block at imprinted goal race pace. mpFraction scales with plan ladder index.",
  },
  {
    name: "Marathon Test",
    workoutType: "LongRun",
    description: "Peak long run with larger goal-pace block.",
    intendedPhase: ["peak"],
    isQuality: true,
    isLongRunQuality: true,
    isMP: true,
    isLadder: false,
    paceAnchor: PACE_ANCHOR_MP_SIMULATION,
    mpFraction: 0.55,
    mpTotalMiles: null,
    mpPaceOffsetSecPerMile: null,
    mpBlockPosition: "BACK_HALF",
    mpBlockProgression: "flat",
    ladderStepMeters: null,
    minLadderMeters: null,
    maxLadderMeters: null,
    progressionIndex: 3,
    workBaseReps: null,
    workBaseRepMeters: null,
    workBaseMiles: null,
    recoveryDistanceMeters: null,
    warmupMiles: null,
    warmupPaceOffsetSecPerMile: null,
    cooldownMiles: null,
    cooldownPaceOffsetSecPerMile: null,
    workPaceOffsetSecPerMile: 0,
    workBasePaceOffsetSecPerMile: null,
    recoveryPaceOffsetSecPerMile: null,
    notes: "Peak long run with larger goal-pace block.",
  },
  {
    name: "Easy Run",
    workoutType: "Easy",
    description: null,
    intendedPhase: ["base", "build", "peak", "taper"],
    isQuality: false,
    isLongRunQuality: false,
    isMP: false,
    isLadder: false,
    paceAnchor: PACE_ANCHOR_CURRENT_BUILDUP,
    mpFraction: null,
    mpTotalMiles: null,
    mpPaceOffsetSecPerMile: null,
    mpBlockPosition: null,
    mpBlockProgression: "flat",
    ladderStepMeters: null,
    minLadderMeters: null,
    maxLadderMeters: null,
    progressionIndex: 1,
    workBaseReps: null,
    workBaseRepMeters: null,
    workBaseMiles: null,
    recoveryDistanceMeters: null,
    warmupMiles: null,
    warmupPaceOffsetSecPerMile: null,
    cooldownMiles: null,
    cooldownPaceOffsetSecPerMile: null,
    workPaceOffsetSecPerMile: 120,
    workBasePaceOffsetSecPerMile: null,
    recoveryPaceOffsetSecPerMile: null,
    notes: null,
  },
];
