/**
 * Athlete-facing plan titles — race from terminal FK is canonical; plan.name is sharing label.
 */

export const AUTO_GENERATED_PLAN_NAME_PREFIX = "Training — ";

export function autoGeneratedPlanName(raceName: string): string {
  const race = raceName.trim();
  return race ? `${AUTO_GENERATED_PLAN_NAME_PREFIX}${race}` : "My Training Plan";
}

/** True when name matches the POST /api/training-plan default for a given race. */
export function isAutoGeneratedPlanName(
  planName: string | null | undefined,
  raceName: string | null | undefined
): boolean {
  const name = planName?.trim();
  const race = raceName?.trim();
  if (!name || !race) return false;
  return name === autoGeneratedPlanName(race);
}

export type PlanRaceDisplaySource = {
  name: string;
  race_registry?: { name: string } | null;
};

/** Primary H1 on athlete training surfaces — terminal race name, not stale plan.name. */
export function planRaceDisplayName(plan: PlanRaceDisplaySource): string {
  const race = plan.race_registry?.name?.trim();
  if (race) return race;
  return plan.name?.trim() || "Training plan";
}

/** Public / share surfaces keep the user-chosen plan.name. */
export function planSharingTitle(plan: { name?: string | null }): string {
  return plan.name?.trim() || "Training plan";
}

/** Name looks customized and may not match the current terminal race. */
export function planTitleRaceMismatch(
  plan: PlanRaceDisplaySource
): boolean {
  const race = plan.race_registry?.name?.trim();
  const name = plan.name?.trim();
  if (!race || !name) return false;
  if (isAutoGeneratedPlanName(name, race)) return false;
  if (name.includes(race)) return false;
  return true;
}

/** Repair when name is exact `Training — {oldRace}` but terminal race differs. */
export function syncAutoGeneratedPlanNameForTerminal(
  planName: string | null | undefined,
  terminalRaceName: string | null | undefined
): string | null {
  const name = planName?.trim();
  const terminal = terminalRaceName?.trim();
  if (!name || !terminal) return null;
  if (!name.startsWith(AUTO_GENERATED_PLAN_NAME_PREFIX)) return null;
  const embeddedRace = name.slice(AUTO_GENERATED_PLAN_NAME_PREFIX.length).trim();
  if (!embeddedRace || embeddedRace === terminal) return null;
  if (name !== autoGeneratedPlanName(embeddedRace)) return null;
  return autoGeneratedPlanName(terminal);
}

/** @deprecated use syncAutoGeneratedPlanNameForTerminal */
export function repairedAutoGeneratedPlanName(params: {
  planName: string | null | undefined;
  previousRaceName: string | null | undefined;
  terminalRaceName: string | null | undefined;
}): string | null {
  const prev = params.previousRaceName?.trim();
  if (prev && isAutoGeneratedPlanName(params.planName, prev)) {
    return syncAutoGeneratedPlanNameForTerminal(
      params.planName,
      params.terminalRaceName
    );
  }
  return syncAutoGeneratedPlanNameForTerminal(
    params.planName,
    params.terminalRaceName
  );
}
