import assert from "node:assert/strict";
import test from "node:test";
import {
  autoGeneratedPlanName,
  isAutoGeneratedPlanName,
  planRaceDisplayName,
  planTitleRaceMismatch,
  syncAutoGeneratedPlanNameForTerminal,
} from "@/lib/training/plan-display-title";

test("autoGeneratedPlanName uses Training — prefix", () => {
  assert.equal(
    autoGeneratedPlanName("Boulderthon Full Marathon"),
    "Training — Boulderthon Full Marathon"
  );
});

test("isAutoGeneratedPlanName matches exact default", () => {
  assert.equal(
    isAutoGeneratedPlanName(
      "Training — Marine Corps Marathon",
      "Marine Corps Marathon"
    ),
    true
  );
  assert.equal(
    isAutoGeneratedPlanName(
      "Training — Boulderthon Full Marathon",
      "Marine Corps Marathon"
    ),
    false
  );
});

test("planRaceDisplayName prefers terminal race over stale plan.name", () => {
  assert.equal(
    planRaceDisplayName({
      name: "Training — Marine Corps Marathon",
      race_registry: { name: "Boulderthon Full Marathon" },
    }),
    "Boulderthon Full Marathon"
  );
});

test("syncAutoGeneratedPlanNameForTerminal repairs stale default name", () => {
  assert.equal(
    syncAutoGeneratedPlanNameForTerminal(
      "Training — Marine Corps Marathon",
      "Boulderthon Full Marathon"
    ),
    "Training — Boulderthon Full Marathon"
  );
});

test("syncAutoGeneratedPlanNameForTerminal skips when already in sync", () => {
  assert.equal(
    syncAutoGeneratedPlanNameForTerminal(
      "Training — Boulderthon Full Marathon",
      "Boulderthon Full Marathon"
    ),
    null
  );
});

test("syncAutoGeneratedPlanNameForTerminal skips custom titles", () => {
  assert.equal(
    syncAutoGeneratedPlanNameForTerminal(
      "Adam's Boulder Build",
      "Boulderthon Full Marathon"
    ),
    null
  );
});

test("planTitleRaceMismatch flags auto-generated name for wrong race", () => {
  assert.equal(
    planTitleRaceMismatch({
      name: "Training — Marine Corps Marathon",
      race_registry: { name: "Boulderthon Full Marathon" },
    }),
    true
  );
});

test("planTitleRaceMismatch clear when title matches terminal", () => {
  assert.equal(
    planTitleRaceMismatch({
      name: "Training — Boulderthon Full Marathon",
      race_registry: { name: "Boulderthon Full Marathon" },
    }),
    false
  );
});
